development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: symphian_dev
  pool: 5
  timeout: 5000
  username: postgres
  password: Pluto64Post

test:
  adapter: postgresql
  database: symphian_test
  pool: 5
  timeout: 5000
  username: postgres
  password: Pluto64Post

# production:
#   adapter: postgresql
#   database: db/production.sqlite3
#   pool: 5
#   timeout: 5000
